[project]
name = "voice-patient-registration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0",
    "uvicorn[standard]>=0.53.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
